### ISSUE TITLE
Support for async Methods in ISubscriber.Subscribe  

### ISSUE THREAD

**Issue by AlexanderFinkbeiner** [choudhurynirjhar/plain-rabbitmq#4]
Is it possible to implement an async Method as a parameter for the `Subscribe` Method in `ISubscriber`.

![image](https://user-images.githubusercontent.com/22540563/108829632-b2e20d00-75c8-11eb-98fb-7722a2d99b06.png)

**Comment by choudhurynirjhar** [comment]
This is definitely doable, I will create a PR soon.

**Comment by AlexanderFinkbeiner** [comment]
Thanks!

**Comment by fdb-development** [comment]
Nice thanks, when do you plan to add it?

**Comment by choudhurynirjhar** [comment]
Added support for async subscription

**Comment by saccoe** [comment]
Subscribe works fine for me but SubscribeAsync does never trigger. Any ideas? My code is exactly the same as the one posted in the image save for the method name.
